START TRANSACTION;
CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" text,
    "Password" text NOT NULL,
    "UserType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UniversityId" integer,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_User_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id")
);

CREATE TABLE "ChatSession" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "Title" text,
    CONSTRAINT "PK_ChatSession" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatSession_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ChatMessage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChatSessionId" integer NOT NULL,
    "Sender" text NOT NULL,
    "Message" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessage_ChatSession_ChatSessionId" FOREIGN KEY ("ChatSessionId") REFERENCES "ChatSession" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatMessage_ChatSessionId" ON "ChatMessage" ("ChatSessionId");

CREATE INDEX "IX_ChatSession_UserId" ON "ChatSession" ("UserId");

CREATE INDEX "IX_User_UniversityId" ON "User" ("UniversityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250605134403_AddUserChatSessionChatMessage', '9.0.5');

COMMIT;

