CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "University" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ShortName" text NOT NULL,
    "Introduction" text NOT NULL,
    "OfficialWebsite" text NOT NULL,
    "AdmissionWebsite" text NOT NULL,
    "Ranking" integer,
    "RankingCriteria" text NOT NULL,
    "Locations" text,
    CONSTRAINT "PK_University" PRIMARY KEY ("Id")
);

CREATE TABLE "AdmissionMethod" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Criteria" text NOT NULL,
    "Year" integer,
    "UniversityId" integer NOT NULL,
    CONSTRAINT "PK_AdmissionMethod" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdmissionMethod_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AdmissionNew" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "PublishDate" timestamp with time zone NOT NULL,
    "Year" integer,
    "UniversityId" integer NOT NULL,
    CONSTRAINT "PK_AdmissionNew" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdmissionNew_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Major" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text NOT NULL,
    "AdmissionScore" numeric(18,2),
    "Year" integer,
    "UniversityId" integer NOT NULL,
    CONSTRAINT "PK_Major" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Major_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Program" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Tuition" numeric(18,2),
    "TuitionUnit" text NOT NULL,
    "Year" integer,
    "UniversityId" integer NOT NULL,
    CONSTRAINT "PK_Program" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Program_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Scholarship" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Value" numeric(18,2),
    "ValueType" text NOT NULL,
    "Criteria" text NOT NULL,
    "Year" integer,
    "UniversityId" integer NOT NULL,
    CONSTRAINT "PK_Scholarship" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Scholarship_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AdmissionCriteria" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "MinimumScore" numeric(18,2),
    "AdmissionMethodId" integer NOT NULL,
    CONSTRAINT "PK_AdmissionCriteria" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdmissionCriteria_AdmissionMethod_AdmissionMethodId" FOREIGN KEY ("AdmissionMethodId") REFERENCES "AdmissionMethod" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AdmissionCriteria_AdmissionMethodId" ON "AdmissionCriteria" ("AdmissionMethodId");

CREATE INDEX "IX_AdmissionMethod_UniversityId" ON "AdmissionMethod" ("UniversityId");

CREATE INDEX "IX_AdmissionNew_UniversityId" ON "AdmissionNew" ("UniversityId");

CREATE INDEX "IX_Major_UniversityId" ON "Major" ("UniversityId");

CREATE INDEX "IX_Program_UniversityId" ON "Program" ("UniversityId");

CREATE INDEX "IX_Scholarship_UniversityId" ON "Scholarship" ("UniversityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250605133352_AddLocationsToUniversity', '9.0.5');

CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" text,
    "Password" text NOT NULL,
    "UserType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UniversityId" integer,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_User_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id")
);

CREATE TABLE "ChatSession" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "Title" text,
    CONSTRAINT "PK_ChatSession" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatSession_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ChatMessage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChatSessionId" integer NOT NULL,
    "Sender" text NOT NULL,
    "Message" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessage_ChatSession_ChatSessionId" FOREIGN KEY ("ChatSessionId") REFERENCES "ChatSession" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatMessage_ChatSessionId" ON "ChatMessage" ("ChatSessionId");

CREATE INDEX "IX_ChatSession_UserId" ON "ChatSession" ("UserId");

CREATE INDEX "IX_User_UniversityId" ON "User" ("UniversityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250605134403_AddUserChatSessionChatMessage', '9.0.5');

ALTER TABLE "User" DROP CONSTRAINT "FK_User_University_UniversityId";

ALTER TABLE "User" DROP COLUMN "Password";

ALTER TABLE "User" DROP COLUMN "UserType";

ALTER TABLE "User" ALTER COLUMN "Username" TYPE character varying(50);
ALTER TABLE "User" ALTER COLUMN "Username" DROP NOT NULL;

ALTER TABLE "User" ALTER COLUMN "Email" TYPE character varying(100);
UPDATE "User" SET "Email" = '' WHERE "Email" IS NULL;
ALTER TABLE "User" ALTER COLUMN "Email" SET NOT NULL;
ALTER TABLE "User" ALTER COLUMN "Email" SET DEFAULT '';

ALTER TABLE "User" ALTER COLUMN "CreatedAt" SET DEFAULT (NOW());

ALTER TABLE "User" ADD "DisplayName" character varying(100);

ALTER TABLE "User" ADD "EmailVerified" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "User" ADD "FirebaseUid" character varying(50);

ALTER TABLE "User" ADD "LastLoginAt" timestamp with time zone;

ALTER TABLE "User" ADD "PasswordHash" character varying(100);

ALTER TABLE "User" ADD "PhotoURL" character varying(500);

ALTER TABLE "User" ADD "Provider" character varying(20) NOT NULL DEFAULT 'email';

ALTER TABLE "User" ADD "Role" character varying(20) NOT NULL DEFAULT 'student';

CREATE UNIQUE INDEX "IX_User_Email" ON "User" ("Email");

CREATE UNIQUE INDEX "IX_User_FirebaseUid" ON "User" ("FirebaseUid");

CREATE UNIQUE INDEX "IX_User_Username" ON "User" ("Username");

ALTER TABLE "User" ADD CONSTRAINT "FK_User_University_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "University" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250608112500_UpdateUserModelForAuthentication', '9.0.5');

ALTER TABLE "Major" ADD "ProgramId" integer;

CREATE INDEX "IX_Major_ProgramId" ON "Major" ("ProgramId");

ALTER TABLE "Major" ADD CONSTRAINT "FK_Major_Program_ProgramId" FOREIGN KEY ("ProgramId") REFERENCES "Program" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250610085321_AddProgramIdToMajor', '9.0.5');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250711103233_FixUniversitySequence', '9.0.5');

COMMIT;

